version: '4'

services:
  mysql-development:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: gymday
    ports:
      - "3308:3306"
  mail:
    image: schickling/mailcatcher
    ports: 
    - 1080:1080